// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRVtLfAMAdyej1hxUQ1mjx3reg1WSy68',
    appId: '1:740606550126:web:fca8cb3e6b51b7efc3867f',
    messagingSenderId: '740606550126',
    projectId: 'localcommunity-f9804',
    authDomain: 'localcommunity-f9804.firebaseapp.com',
    storageBucket: 'localcommunity-f9804.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6U-59XyzgBzt_4eN2JV68K_g2f3-gR2Q',
    appId: '1:740606550126:android:df57848fa8205882c3867f',
    messagingSenderId: '740606550126',
    projectId: 'localcommunity-f9804',
    storageBucket: 'localcommunity-f9804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvorncji9LOJF5HdCewL3IgWldBLvMEEY',
    appId: '1:740606550126:ios:4b9b345452455198c3867f',
    messagingSenderId: '740606550126',
    projectId: 'localcommunity-f9804',
    storageBucket: 'localcommunity-f9804.appspot.com',
    iosBundleId: 'com.example.localCommunityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvorncji9LOJF5HdCewL3IgWldBLvMEEY',
    appId: '1:740606550126:ios:f5b136a9dce677a3c3867f',
    messagingSenderId: '740606550126',
    projectId: 'localcommunity-f9804',
    storageBucket: 'localcommunity-f9804.appspot.com',
    iosBundleId: 'com.example.localCommunityApp.RunnerTests',
  );
}
